---
abstract: 'work with Mac plists at a low level, fast'
author:
  - 'Darren M. Kulp, C<< <darren@kulp.ch> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  LWP: 0
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mac-PropertyList-SAX
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0
  HTML::Entities: 0
  HTML::Entities::Numbered: 0.04
  MIME::Base64: 0
  Mac::PropertyList: 1.601
  Object::MultiType: 0.02
  XML::SAX::Base: 0
  XML::SAX::Expat: 0.4
  XML::SAX::ParserFactory: 0
  constant: 1.06
  enum: 0
resources:
  license: http://dev.perl.org/licenses/
version: '1.001'
